8294549: configure script should detect unsupported path
The OpenJDK build system does not support building when the source code
resides on a path that contains a space. This requirement is documented in the
build instructions but not enforced by the configure script.

This change adds an explicit checks to the wrapper `configure` script that fail
the build if the source code to be built is located in a directory who's path
contains a space character or the build path cannot be determined.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2012, 2014, Oracle and/or its affiliates. All rights reserved.
+# Copyright (c) 2012, 2022, Oracle and/or its affiliates. All rights reserved.
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 #
 # This code is free software; you can redistribute it and/or modify it
@@ -26,8 +26,29 @@
 # make sure that is called using bash.
 
 # Get an absolute path to this script, since that determines the top-level directory.
-this_script_dir=`dirname $0`
-this_script_dir=`cd $this_script_dir > /dev/null && pwd`
+source_path="${BASH_SOURCE[0]:-$0}"
+if [[ ${source_path} = */* ]]; then
+	source_path=${source_path%/*}/
+else
+	source_path=./
+fi
+
+if [ -z "${source_path}" ]; then
+	echo "# Could not determine location of configure script"
+	exit 1
+fi
+
+this_script_dir="$(cd -- "${source_path}" > /dev/null && pwd)"
+
+if [ -z "${this_script_dir}" ]; then
+	echo "# Could not determine location of configure script"
+	exit 1
+fi
+
+if [[ "${this_script_dir}" =~ .*[[:space:]]+.* ]]; then
+	echo "# Build path containing space character is not supported"
+	exit 1
+fi
 
 # Delegate to wrapper, forcing wrapper to believe $0 is this script by using -c.
 # This trick is needed to get autoconf to co-operate properly.
